server:
  port: 8000

spring:
  application:
    name: intervention-app
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/intervention
    username: intervention
    password: intervention
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
